name: Build
env:
  tag_regex_st: '^v?[0-9]+.[0-9]+.[0-9]+$'
  tag_regex_rc: '^v?[0-9]+.[0-9]+.[0-9]+rc[0-9]+$'
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Get the Ref
      id: get-ref
      uses: ankitvgupta/ref-to-tag-action@master
      with:
        ref: ${{ github.ref }}
        head_ref: ${{ github.head_ref }}

    - name: Set Stable Flag
      id: is-stable
      run: |
        [[ ${{ steps.get-ref.outputs.tag }} =~ ${{ env.tag_regex_st }} ]] && {
              echo "match=true" >> $GITHUB_OUTPUT
              echo "Build triggered on stable release"
        }

    - name: Set RC Flag
      id: is-rc
      run: |
        [[ ${{ steps.get-ref.outputs.tag }} =~ ${{ env.tag_regex_rc }} ]] && {
              echo "match=true" >> $GITHUB_OUTPUT
              echo "Build triggered on stable release"
        }

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        $${{ steps.is-rc.outputs.match }} && echo "Building a release candidate ..."
        $${{ steps.is-stable.outputs.match }} && echo "Building a stable release ..."

    - name: Create Release
      id: create_release
      if: steps.is-stable.outputs.match == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Create PreRelease
      id: create_prerelease
      if: steps.is-rc.outputs.match == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

